'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LTFSCopyGUI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dragdrop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dragdrop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 许可证文本显示.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_Application_License() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_Application_License", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 复制文件信息到剪贴板.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_FileBrowser_CopyInfo() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_FileBrowser_CopyInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 重新校验.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_HashTaskWindow_ReHash() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_HashTaskWindow_ReHash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 目标路径.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_IndexAnalyzer_Dest() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_IndexAnalyzer_Dest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 生成命令行.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_IndexAnalyzer_GenCMD() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_IndexAnalyzer_GenCMD", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 上一次的文件.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_IndexAnalyzer_LastFile() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_IndexAnalyzer_LastFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 源路径.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_IndexAnalyzer_Src() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_IndexAnalyzer_Src", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 自动刷新设备列表.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSConf_AutoRefresh() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSConf_AutoRefresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 容量损失判定速度下限.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_AutoCleanDownLim() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_AutoCleanDownLim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 容量损失检测错误率指数下限.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_AutoCleanErrRateLogThreashould() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_AutoCleanErrRateLogThreashould", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 容量损失判定秒数.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_AutoCleanTimeThreashould() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_AutoCleanTimeThreashould", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 容量损失判定速度上限.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_AutoCleanUpperLim() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_AutoCleanUpperLim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 容量损失自动停顿.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_AutoFlush() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_AutoFlush", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 容量显示刷新间隔.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_CapacityRefreshInterval() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_CapacityRefreshInterval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 重装带前清洁次数.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_CleanCycle() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_CleanCycle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 去重.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_DeDupe() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_DeDupe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 禁用分区.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_DisablePartition() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_DisablePartition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 文件标签设置.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_FileLabel() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_FileLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 总是更新数据区索引.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_ForceIndex() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_ForceIndex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 异步校验
        '''性能更好，但CPU使用率更高
        '''仅当计算校验开启有效.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_HashAsync() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_HashAsync", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 计算校验.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_HashOnWriting() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_HashOnWriting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引更新间隔（字节）.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_IndexWriteInterval() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_IndexWriteInterval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 启用日志.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_LogEnabled() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_LogEnabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 写入完成后：
        '''  0 - 什么都不做
        '''  1 - 更新数据区索引
        '''  2 - 更新全部索引
        '''  3 - 更新全部索引并弹出.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_OnWriteFinished() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_OnWriteFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 添加文件时覆盖已有文件.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_OverwriteExist() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_OverwriteExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 写入开始时切换电源策略.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_PowerPolicyOnWriteBegin() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_PowerPolicyOnWriteBegin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 写入结束后切换电源策略.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_PowerPolicyOnWriteEnd() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_PowerPolicyOnWriteEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 预读字节数.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_PreLoadBytes() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_PreLoadBytes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 预读文件数.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_PreLoadFileCount() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_PreLoadFileCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 显示文件数.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_ShowFileCount() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_ShowFileCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 显示容量损失.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_ShowLoss() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_ShowLoss", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 添加文件时跳过符号链接.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_LTFSWriter_SkipSymlink() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_LTFSWriter_SkipSymlink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 条码，0-20个ASCII字符，默认为空.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_mkltfs_Barcode() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_mkltfs_Barcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 块大小，1-2097152，默认为524288.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_mkltfs_BlockLen() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_mkltfs_BlockLen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 磁带容量，0-65535，默认为65535.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_mkltfs_Capacity() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_mkltfs_Capacity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 加密密钥.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_mkltfs_EncryptionKey() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_mkltfs_EncryptionKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 用于控制是否分区，0或者1，默认为1.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_mkltfs_ExtraPartitionCount() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_mkltfs_ExtraPartitionCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 立即模式。此处无效.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_mkltfs_ImmediateMode() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_mkltfs_ImmediateMode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 当前支持的额外分区数量。只读.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_mkltfs_MaxExtraPartitionAllowed() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_mkltfs_MaxExtraPartitionAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 分区0大小，单位为GB，将向上取整到偶数个wrap，默认为1
        '''P0Size和P1Size至多一个为65535，表示取剩余空间
        '''P0Size和P1Size如果都不为65535，则两者总和不得超过磁带容量.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_mkltfs_P0Size() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_mkltfs_P0Size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to P1Size: 分区1大小，单位为GB，将向上取整到偶数个wrap，默认为65535
        '''P0Size和P1Size至多一个为65535，表示取剩余空间
        '''P0Size和P1Size如果都不为65535，则两者总和不得超过磁带容量.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_mkltfs_P1Size() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_mkltfs_P1Size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 卷标，任意长度Unicode字符，默认为空.
        '''</summary>
        Friend ReadOnly Property PropertyDescription_mkltfs_VolumeLabel() As String
            Get
                Return ResourceManager.GetString("PropertyDescription_mkltfs_VolumeLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 资源.
        '''</summary>
        Friend ReadOnly Property ResText_() As String
            Get
                Return ResourceManager.GetString("ResText_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 添加完成.
        '''</summary>
        Friend ReadOnly Property ResText_AddFin() As String
            Get
                Return ResourceManager.GetString("ResText_AddFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在添加.
        '''</summary>
        Friend ReadOnly Property ResText_Adding() As String
            Get
                Return ResourceManager.GetString("ResText_Adding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在解析索引.
        '''</summary>
        Friend ReadOnly Property ResText_AI() As String
            Get
                Return ResourceManager.GetString("ResText_AI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引解析成功.
        '''</summary>
        Friend ReadOnly Property ResText_AISucc() As String
            Get
                Return ResourceManager.GetString("ResText_AISucc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 平均速度.
        '''</summary>
        Friend ReadOnly Property ResText_AvgS() As String
            Get
                Return ResourceManager.GetString("ResText_AvgS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 磁带标签.
        '''</summary>
        Friend ReadOnly Property ResText_Barcode() As String
            Get
                Return ResourceManager.GetString("ResText_Barcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 磁带标签：.
        '''</summary>
        Friend ReadOnly Property ResText_Barcode2() As String
            Get
                Return ResourceManager.GetString("ResText_Barcode2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 块大小.
        '''</summary>
        Friend ReadOnly Property ResText_BlkSize() As String
            Get
                Return ResourceManager.GetString("ResText_BlkSize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 块.
        '''</summary>
        Friend ReadOnly Property ResText_Block() As String
            Get
                Return ResourceManager.GetString("ResText_Block", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 操作执行中.
        '''</summary>
        Friend ReadOnly Property ResText_Busy() As String
            Get
                Return ResourceManager.GetString("ResText_Busy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 字节.
        '''</summary>
        Friend ReadOnly Property ResText_Byte() As String
            Get
                Return ResourceManager.GetString("ResText_Byte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 清洁磁头.
        '''</summary>
        Friend ReadOnly Property ResText_C0() As String
            Get
                Return ResourceManager.GetString("ResText_C0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 检测到容量缺失次数：.
        '''</summary>
        Friend ReadOnly Property ResText_C1() As String
            Get
                Return ResourceManager.GetString("ResText_C1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 上次清洁：.
        '''</summary>
        Friend ReadOnly Property ResText_C2() As String
            Get
                Return ResourceManager.GetString("ResText_C2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 此时取消会丢失未写完的文件，是否继续.
        '''</summary>
        Friend ReadOnly Property ResText_CancelConfirm() As String
            Get
                Return ResourceManager.GetString("ResText_CancelConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 显示容量损失会大大降低写入性能。仍要开启？.
        '''</summary>
        Friend ReadOnly Property ResText_CapLossPerfWarning() As String
            Get
                Return ResourceManager.GetString("ResText_CapLossPerfWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 可用空间.
        '''</summary>
        Friend ReadOnly Property ResText_CapRem() As String
            Get
                Return ResourceManager.GetString("ResText_CapRem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在计算校验.
        '''</summary>
        Friend ReadOnly Property ResText_CHashing() As String
            Get
                Return ResourceManager.GetString("ResText_CHashing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 确定要清零写入计数？.
        '''</summary>
        Friend ReadOnly Property ResText_ClearWC() As String
            Get
                Return ResourceManager.GetString("ResText_ClearWC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 剪贴板.
        '''</summary>
        Friend ReadOnly Property ResText_ClipBoard() As String
            Get
                Return ResourceManager.GetString("ResText_ClipBoard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置重装带前清洁次数.
        '''</summary>
        Friend ReadOnly Property ResText_CLNCS() As String
            Get
                Return ResourceManager.GetString("ResText_CLNCS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 确认.
        '''</summary>
        Friend ReadOnly Property ResText_Confirm() As String
            Get
                Return ResourceManager.GetString("ResText_Confirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 容量刷新间隔：禁用.
        '''</summary>
        Friend ReadOnly Property ResText_CRDisabled() As String
            Get
                Return ResourceManager.GetString("ResText_CRDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 可用容量已刷新.
        '''</summary>
        Friend ReadOnly Property ResText_CRef() As String
            Get
                Return ResourceManager.GetString("ResText_CRef", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 可用容量刷新失败.
        '''</summary>
        Friend ReadOnly Property ResText_CRefErr() As String
            Get
                Return ResourceManager.GetString("ResText_CRefErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 容量刷新间隔：.
        '''</summary>
        Friend ReadOnly Property ResText_CRIntv() As String
            Get
                Return ResourceManager.GetString("ResText_CRIntv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 当前位置.
        '''</summary>
        Friend ReadOnly Property ResText_CurPos() As String
            Get
                Return ResourceManager.GetString("ResText_CurPos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 全部数据将丢失且无法恢复，是否继续？.
        '''</summary>
        Friend ReadOnly Property ResText_DataLossWarning() As String
            Get
                Return ResourceManager.GetString("ResText_DataLossWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 是否删除 .
        '''</summary>
        Friend ReadOnly Property ResText_DelConfrm() As String
            Get
                Return ResourceManager.GetString("ResText_DelConfrm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 目录名.
        '''</summary>
        Friend ReadOnly Property ResText_DirName() As String
            Get
                Return ResourceManager.GetString("ResText_DirName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 存在重名目录.
        '''</summary>
        Friend ReadOnly Property ResText_DirNExist() As String
            Get
                Return ResourceManager.GetString("ResText_DirNExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 目录名存在非法字符.
        '''</summary>
        Friend ReadOnly Property ResText_DirNIllegal() As String
            Get
                Return ResourceManager.GetString("ResText_DirNIllegal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 标签后缀已修改为.
        '''</summary>
        Friend ReadOnly Property ResText_DLFin() As String
            Get
                Return ResourceManager.GetString("ResText_DLFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置目录标签后缀.
        '''</summary>
        Friend ReadOnly Property ResText_DLS() As String
            Get
                Return ResourceManager.GetString("ResText_DLS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 标签工具.
        '''</summary>
        Friend ReadOnly Property ResText_DLT() As String
            Get
                Return ResourceManager.GetString("ResText_DLT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 未写入数据.
        '''</summary>
        Friend ReadOnly Property ResText_DNW() As String
            Get
                Return ResourceManager.GetString("ResText_DNW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 数据区索引已更新.
        '''</summary>
        Friend ReadOnly Property ResText_DPIUed() As String
            Get
                Return ResourceManager.GetString("ResText_DPIUed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 写入数据区索引失败.
        '''</summary>
        Friend ReadOnly Property ResText_DPIWFailed() As String
            Get
                Return ResourceManager.GetString("ResText_DPIWFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 已写入数据区索引.
        '''</summary>
        Friend ReadOnly Property ResText_DPIWritten() As String
            Get
                Return ResourceManager.GetString("ResText_DPIWritten", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 当前无法进行拖放操作.
        '''</summary>
        Friend ReadOnly Property ResText_DragNA() As String
            Get
                Return ResourceManager.GetString("ResText_DragNA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 磁带已弹出.
        '''</summary>
        Friend ReadOnly Property ResText_Ejd() As String
            Get
                Return ResourceManager.GetString("ResText_Ejd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 错误.
        '''</summary>
        Friend ReadOnly Property ResText_Error() As String
            Get
                Return ResourceManager.GetString("ResText_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 获取分区信息出错.
        '''</summary>
        Friend ReadOnly Property ResText_ErrP() As String
            Get
                Return ResourceManager.GetString("ResText_ErrP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 错误率指数：.
        '''</summary>
        Friend ReadOnly Property ResText_ErrRateLog() As String
            Get
                Return ResourceManager.GetString("ResText_ErrRateLog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 磁带即将写满.
        '''</summary>
        Friend ReadOnly Property ResText_EWEOM() As String
            Get
                Return ResourceManager.GetString("ResText_EWEOM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在导出.
        '''</summary>
        Friend ReadOnly Property ResText_Exporting() As String
            Get
                Return ResourceManager.GetString("ResText_Exporting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 文件缓存：.
        '''</summary>
        Friend ReadOnly Property ResText_FB() As String
            Get
                Return ResourceManager.GetString("ResText_FB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 文件数：.
        '''</summary>
        Friend ReadOnly Property ResText_FCountP() As String
            Get
                Return ResourceManager.GetString("ResText_FCountP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 文件打开出错.
        '''</summary>
        Friend ReadOnly Property ResText_FileOpenError() As String
            Get
                Return ResourceManager.GetString("ResText_FileOpenError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 每秒文件.
        '''</summary>
        Friend ReadOnly Property ResText_FileRateBT() As String
            Get
                Return ResourceManager.GetString("ResText_FileRateBT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 个文件？.
        '''</summary>
        Friend ReadOnly Property ResText_Files_C() As String
            Get
                Return ResourceManager.GetString("ResText_Files_C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 格式化失败.
        '''</summary>
        Friend ReadOnly Property ResText_FmtFail() As String
            Get
                Return ResourceManager.GetString("ResText_FmtFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 格式化完成.
        '''</summary>
        Friend ReadOnly Property ResText_FmtFin() As String
            Get
                Return ResourceManager.GetString("ResText_FmtFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 存在重名文件.
        '''</summary>
        Friend ReadOnly Property ResText_FNExist() As String
            Get
                Return ResourceManager.GetString("ResText_FNExist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 文件名存在非法字符.
        '''</summary>
        Friend ReadOnly Property ResText_FNIllegal() As String
            Get
                Return ResourceManager.GetString("ResText_FNIllegal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 大小：.
        '''</summary>
        Friend ReadOnly Property ResText_FSizeP() As String
            Get
                Return ResourceManager.GetString("ResText_FSizeP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在生成索引.
        '''</summary>
        Friend ReadOnly Property ResText_GI() As String
            Get
                Return ResourceManager.GetString("ResText_GI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在校验.
        '''</summary>
        Friend ReadOnly Property ResText_Hashing() As String
            Get
                Return ResourceManager.GetString("ResText_Hashing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 校验出错.
        '''</summary>
        Friend ReadOnly Property ResText_HErr() As String
            Get
                Return ResourceManager.GetString("ResText_HErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 校验完成.
        '''</summary>
        Friend ReadOnly Property ResText_HFin() As String
            Get
                Return ResourceManager.GetString("ResText_HFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 提示.
        '''</summary>
        Friend ReadOnly Property ResText_Hint() As String
            Get
                Return ResourceManager.GetString("ResText_Hint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 文件解析出错：.
        '''</summary>
        Friend ReadOnly Property ResText_IAErrp() As String
            Get
                Return ResourceManager.GetString("ResText_IAErrp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 空闲.
        '''</summary>
        Friend ReadOnly Property ResText_Idle() As String
            Get
                Return ResourceManager.GetString("ResText_Idle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 已加载索引，请自行确保索引一致性.
        '''</summary>
        Friend ReadOnly Property ResText_ILdedP() As String
            Get
                Return ResourceManager.GetString("ResText_ILdedP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 导入完成.
        '''</summary>
        Friend ReadOnly Property ResText_Imported() As String
            Get
                Return ResourceManager.GetString("ResText_Imported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在导入.
        '''</summary>
        Friend ReadOnly Property ResText_Importing() As String
            Get
                Return ResourceManager.GetString("ResText_Importing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引.
        '''</summary>
        Friend ReadOnly Property ResText_Index() As String
            Get
                Return ResourceManager.GetString("ResText_Index", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引已备份至.
        '''</summary>
        Friend ReadOnly Property ResText_IndexBak2() As String
            Get
                Return ResourceManager.GetString("ResText_IndexBak2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引已备份.
        '''</summary>
        Friend ReadOnly Property ResText_IndexBaked() As String
            Get
                Return ResourceManager.GetString("ResText_IndexBaked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引备份失败.
        '''</summary>
        Friend ReadOnly Property ResText_IndexBakF() As String
            Get
                Return ResourceManager.GetString("ResText_IndexBakF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引间隔：.
        '''</summary>
        Friend ReadOnly Property ResText_IndexInterval() As String
            Get
                Return ResourceManager.GetString("ResText_IndexInterval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 不允许写入新的索引.
        '''</summary>
        Friend ReadOnly Property ResText_IndexNAllowed() As String
            Get
                Return ResourceManager.GetString("ResText_IndexNAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 当前为索引区，操作取消.
        '''</summary>
        Friend ReadOnly Property ResText_IPCanc() As String
            Get
                Return ResourceManager.GetString("ResText_IPCanc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引读取失败.
        '''</summary>
        Friend ReadOnly Property ResText_IRFailed() As String
            Get
                Return ResourceManager.GetString("ResText_IRFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引读取成功.
        '''</summary>
        Friend ReadOnly Property ResText_IRSucc() As String
            Get
                Return ResourceManager.GetString("ResText_IRSucc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 个项目.
        '''</summary>
        Friend ReadOnly Property ResText_Items_x() As String
            Get
                Return ResourceManager.GetString("ResText_Items_x", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引已更新.
        '''</summary>
        Friend ReadOnly Property ResText_IUd() As String
            Get
                Return ResourceManager.GetString("ResText_IUd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引更新出错.
        '''</summary>
        Friend ReadOnly Property ResText_IUErr() As String
            Get
                Return ResourceManager.GetString("ResText_IUErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 已定位到.
        '''</summary>
        Friend ReadOnly Property ResText_Located() As String
            Get
                Return ResourceManager.GetString("ResText_Located", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在定位.
        '''</summary>
        Friend ReadOnly Property ResText_Locating() As String
            Get
                Return ResourceManager.GetString("ResText_Locating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 减少锁定.
        '''</summary>
        Friend ReadOnly Property ResText_LockDec() As String
            Get
                Return ResourceManager.GetString("ResText_LockDec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 增加锁定.
        '''</summary>
        Friend ReadOnly Property ResText_LockInc() As String
            Get
                Return ResourceManager.GetString("ResText_LockInc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LTFS卷标.
        '''</summary>
        Friend ReadOnly Property ResText_LTFSVolumeN() As String
            Get
                Return ResourceManager.GetString("ResText_LTFSVolumeN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LTFS卷标：.
        '''</summary>
        Friend ReadOnly Property ResText_LTFSVolumeN2() As String
            Get
                Return ResourceManager.GetString("ResText_LTFSVolumeN2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 导航出错，请重试.
        '''</summary>
        Friend ReadOnly Property ResText_NavErr() As String
            Get
                Return ResourceManager.GetString("ResText_NavErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 新建目录.
        '''</summary>
        Friend ReadOnly Property ResText_NewDir() As String
            Get
                Return ResourceManager.GetString("ResText_NewDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 新文件名.
        '''</summary>
        Friend ReadOnly Property ResText_NFName() As String
            Get
                Return ResourceManager.GetString("ResText_NFName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ，会丢失该位置后的数据，继续？.
        '''</summary>
        Friend ReadOnly Property ResText_NHWrn() As String
            Get
                Return ResourceManager.GetString("ResText_NHWrn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 未加载索引.
        '''</summary>
        Friend ReadOnly Property ResText_NIndex() As String
            Get
                Return ResourceManager.GetString("ResText_NIndex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 未找到LTFS.
        '''</summary>
        Friend ReadOnly Property ResText_NLTFS() As String
            Get
                Return ResourceManager.GetString("ResText_NLTFS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引间隔：禁用自动索引.
        '''</summary>
        Friend ReadOnly Property ResText_NoIndex() As String
            Get
                Return ResourceManager.GetString("ResText_NoIndex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 限速：无限制.
        '''</summary>
        Friend ReadOnly Property ResText_NoSLim() As String
            Get
                Return ResourceManager.GetString("ResText_NoSLim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 未就绪.
        '''</summary>
        Friend ReadOnly Property ResText_NotReady() As String
            Get
                Return ResourceManager.GetString("ResText_NotReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 未找到VOL1.
        '''</summary>
        Friend ReadOnly Property ResText_NVOL1() As String
            Get
                Return ResourceManager.GetString("ResText_NVOL1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 操作取消.
        '''</summary>
        Friend ReadOnly Property ResText_OpCancelled() As String
            Get
                Return ResourceManager.GetString("ResText_OpCancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 操作成功.
        '''</summary>
        Friend ReadOnly Property ResText_OpSucc() As String
            Get
                Return ResourceManager.GetString("ResText_OpSucc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 其他.
        '''</summary>
        Friend ReadOnly Property ResText_Other() As String
            Get
                Return ResourceManager.GetString("ResText_Other", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 覆盖不同文件：.
        '''</summary>
        Friend ReadOnly Property ResText_OverwritingDF() As String
            Get
                Return ResourceManager.GetString("ResText_OverwritingDF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 分区.
        '''</summary>
        Friend ReadOnly Property ResText_Partition() As String
            Get
                Return ResourceManager.GetString("ResText_Partition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 现在可以安全弹出了。是否弹出？.
        '''</summary>
        Friend ReadOnly Property ResText_PEj() As String
            Get
                Return ResourceManager.GetString("ResText_PEj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 预读文件数：.
        '''</summary>
        Friend ReadOnly Property ResText_PFC() As String
            Get
                Return ResourceManager.GetString("ResText_PFC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在准备文件.
        '''</summary>
        Friend ReadOnly Property ResText_PrepFile() As String
            Get
                Return ResourceManager.GetString("ResText_PrepFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 准备写入.
        '''</summary>
        Friend ReadOnly Property ResText_PrepW() As String
            Get
                Return ResourceManager.GetString("ResText_PrepW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 此前.
        '''</summary>
        Friend ReadOnly Property ResText_Previous() As String
            Get
                Return ResourceManager.GetString("ResText_Previous", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 当前第.
        '''</summary>
        Friend ReadOnly Property ResText_RB1() As String
            Get
                Return ResourceManager.GetString("ResText_RB1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 代索引位置:.
        '''</summary>
        Friend ReadOnly Property ResText_RB2() As String
            Get
                Return ResourceManager.GetString("ResText_RB2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 上一代索引位置:.
        '''</summary>
        Friend ReadOnly Property ResText_RB3() As String
            Get
                Return ResourceManager.GetString("ResText_RB3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 未索引的数据将丢失，且回滚后一旦继续写入将丢失后面数据，是否继续.
        '''</summary>
        Friend ReadOnly Property ResText_RB4() As String
            Get
                Return ResourceManager.GetString("ResText_RB4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 重装带前清洁次数：.
        '''</summary>
        Friend ReadOnly Property ResText_RBC() As String
            Get
                Return ResourceManager.GetString("ResText_RBC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 重装带前清洁次数：禁用重装带.
        '''</summary>
        Friend ReadOnly Property ResText_RBCoff() As String
            Get
                Return ResourceManager.GetString("ResText_RBCoff", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 回滚完成.
        '''</summary>
        Friend ReadOnly Property ResText_RBFin() As String
            Get
                Return ResourceManager.GetString("ResText_RBFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在回滚.
        '''</summary>
        Friend ReadOnly Property ResText_RBing() As String
            Get
                Return ResourceManager.GetString("ResText_RBing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 获取容量失败.
        '''</summary>
        Friend ReadOnly Property ResText_RCErr() As String
            Get
                Return ResourceManager.GetString("ResText_RCErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 刷新显示失败.
        '''</summary>
        Friend ReadOnly Property ResText_RDErr() As String
            Get
                Return ResourceManager.GetString("ResText_RDErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 剩余.
        '''</summary>
        Friend ReadOnly Property ResText_Remaining() As String
            Get
                Return ResourceManager.GetString("ResText_Remaining", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 重命名.
        '''</summary>
        Friend ReadOnly Property ResText_Rename() As String
            Get
                Return ResourceManager.GetString("ResText_Rename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 重命名目录.
        '''</summary>
        Friend ReadOnly Property ResText_RenameDir() As String
            Get
                Return ResourceManager.GetString("ResText_RenameDir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 提取出错：SCSI指令执行失败.
        '''</summary>
        Friend ReadOnly Property ResText_RErrSCSI() As String
            Get
                Return ResourceManager.GetString("ResText_RErrSCSI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在提取文件.
        '''</summary>
        Friend ReadOnly Property ResText_RestFile() As String
            Get
                Return ResourceManager.GetString("ResText_RestFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 提取完成.
        '''</summary>
        Friend ReadOnly Property ResText_RestFin() As String
            Get
                Return ResourceManager.GetString("ResText_RestFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 提取出错.
        '''</summary>
        Friend ReadOnly Property ResText_RestoreErr() As String
            Get
                Return ResourceManager.GetString("ResText_RestoreErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在提取.
        '''</summary>
        Friend ReadOnly Property ResText_Restoring() As String
            Get
                Return ResourceManager.GetString("ResText_Restoring", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 读取失败.
        '''</summary>
        Friend ReadOnly Property ResText_RFailed() As String
            Get
                Return ResourceManager.GetString("ResText_RFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在读取索引.
        '''</summary>
        Friend ReadOnly Property ResText_RI() As String
            Get
                Return ResourceManager.GetString("ResText_RI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在读取LTFS信息.
        '''</summary>
        Friend ReadOnly Property ResText_RLTFSInfo() As String
            Get
                Return ResourceManager.GetString("ResText_RLTFSInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 已回到索引位置.
        '''</summary>
        Friend ReadOnly Property ResText_RollBacked() As String
            Get
                Return ResourceManager.GetString("ResText_RollBacked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 获取位置出错.
        '''</summary>
        Friend ReadOnly Property ResText_RPosErr() As String
            Get
                Return ResourceManager.GetString("ResText_RPosErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 速度:.
        '''</summary>
        Friend ReadOnly Property ResText_S0() As String
            Get
                Return ResourceManager.GetString("ResText_S0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 累计:.
        '''</summary>
        Friend ReadOnly Property ResText_S1() As String
            Get
                Return ResourceManager.GetString("ResText_S1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 待处理:.
        '''</summary>
        Friend ReadOnly Property ResText_S2() As String
            Get
                Return ResourceManager.GetString("ResText_S2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 待索引:.
        '''</summary>
        Friend ReadOnly Property ResText_S3() As String
            Get
                Return ResourceManager.GetString("ResText_S3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 进度:.
        '''</summary>
        Friend ReadOnly Property ResText_S4() As String
            Get
                Return ResourceManager.GetString("ResText_S4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置容量刷新间隔（秒）.
        '''</summary>
        Friend ReadOnly Property ResText_SCIntv() As String
            Get
                Return ResourceManager.GetString("ResText_SCIntv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置标签.
        '''</summary>
        Friend ReadOnly Property ResText_SetBarcode() As String
            Get
                Return ResourceManager.GetString("ResText_SetBarcode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 将当前位置.
        '''</summary>
        Friend ReadOnly Property ResText_SetH1() As String
            Get
                Return ResourceManager.GetString("ResText_SetH1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置为数据高度，是否继续？.
        '''</summary>
        Friend ReadOnly Property ResText_SetH2() As String
            Get
                Return ResourceManager.GetString("ResText_SetH2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 如果不明白该操作含义，请点取消.
        '''</summary>
        Friend ReadOnly Property ResText_SetH3() As String
            Get
                Return ResourceManager.GetString("ResText_SetH3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置.
        '''</summary>
        Friend ReadOnly Property ResText_Setting() As String
            Get
                Return ResourceManager.GetString("ResText_Setting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置卷标.
        '''</summary>
        Friend ReadOnly Property ResText_SetVolumeN() As String
            Get
                Return ResourceManager.GetString("ResText_SetVolumeN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置文件缓存.
        '''</summary>
        Friend ReadOnly Property ResText_SFB() As String
            Get
                Return ResourceManager.GetString("ResText_SFB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 是否覆盖现有SHA1？.
        '''</summary>
        Friend ReadOnly Property ResText_SHA1Overw() As String
            Get
                Return ResourceManager.GetString("ResText_SHA1Overw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置索引间隔（字节）.
        '''</summary>
        Friend ReadOnly Property ResText_SIIntv() As String
            Get
                Return ResourceManager.GetString("ResText_SIIntv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 大小.
        '''</summary>
        Friend ReadOnly Property ResText_Size() As String
            Get
                Return ResourceManager.GetString("ResText_Size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 跳过.
        '''</summary>
        Friend ReadOnly Property ResText_Skip() As String
            Get
                Return ResourceManager.GetString("ResText_Skip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 限速：.
        '''</summary>
        Friend ReadOnly Property ResText_SLim() As String
            Get
                Return ResourceManager.GetString("ResText_SLim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 速度上限：.
        '''</summary>
        Friend ReadOnly Property ResText_SMax() As String
            Get
                Return ResourceManager.GetString("ResText_SMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 速度下限：.
        '''</summary>
        Friend ReadOnly Property ResText_SMin() As String
            Get
                Return ResourceManager.GetString("ResText_SMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 速度 (MiB/s).
        '''</summary>
        Friend ReadOnly Property ResText_SpeedBT() As String
            Get
                Return ResourceManager.GetString("ResText_SpeedBT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置预读文件数.
        '''</summary>
        Friend ReadOnly Property ResText_SPreR() As String
            Get
                Return ResourceManager.GetString("ResText_SPreR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置检测速度上限 (MiB/s).
        '''</summary>
        Friend ReadOnly Property ResText_SSMax() As String
            Get
                Return ResourceManager.GetString("ResText_SSMax", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置检测速度下限 (MiB/s).
        '''</summary>
        Friend ReadOnly Property ResText_SSMin() As String
            Get
                Return ResourceManager.GetString("ResText_SSMin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置检测速度持续时间（秒）.
        '''</summary>
        Friend ReadOnly Property ResText_SSTime() As String
            Get
                Return ResourceManager.GetString("ResText_SSTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 持续时间：.
        '''</summary>
        Friend ReadOnly Property ResText_STime() As String
            Get
                Return ResourceManager.GetString("ResText_STime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 操作成功完成.
        '''</summary>
        Friend ReadOnly Property ResText_Succ() As String
            Get
                Return ResourceManager.GetString("ResText_Succ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 保存备份文件.
        '''</summary>
        Friend ReadOnly Property ResText_SvBak() As String
            Get
                Return ResourceManager.GetString("ResText_SvBak", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 需管理员权限重新启动。是否继续？.
        '''</summary>
        Friend ReadOnly Property ResText_UACConfirm() As String
            Get
                Return ResourceManager.GetString("ResText_UACConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在更新数据区索引.
        '''</summary>
        Friend ReadOnly Property ResText_UDI() As String
            Get
                Return ResourceManager.GetString("ResText_UDI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在更新索引.
        '''</summary>
        Friend ReadOnly Property ResText_UI() As String
            Get
                Return ResourceManager.GetString("ResText_UI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 是否更新全部索引并弹出？.
        '''</summary>
        Friend ReadOnly Property ResText_UIE() As String
            Get
                Return ResourceManager.GetString("ResText_UIE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 当前磁带VCI数据：.
        '''</summary>
        Friend ReadOnly Property ResText_VCID() As String
            Get
                Return ResourceManager.GetString("ResText_VCID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 磁带已满.
        '''</summary>
        Friend ReadOnly Property ResText_VOF() As String
            Get
                Return ResourceManager.GetString("ResText_VOF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 警告.
        '''</summary>
        Friend ReadOnly Property ResText_Warning() As String
            Get
                Return ResourceManager.GetString("ResText_Warning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 写入取消.
        '''</summary>
        Friend ReadOnly Property ResText_WCnd() As String
            Get
                Return ResourceManager.GetString("ResText_WCnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 写入出错.
        '''</summary>
        Friend ReadOnly Property ResText_WErr() As String
            Get
                Return ResourceManager.GetString("ResText_WErr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 写入出错：SCSI指令执行失败.
        '''</summary>
        Friend ReadOnly Property ResText_WErrSCSI() As String
            Get
                Return ResourceManager.GetString("ResText_WErrSCSI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 写入完成，耗时.
        '''</summary>
        Friend ReadOnly Property ResText_WFTime() As String
            Get
                Return ResourceManager.GetString("ResText_WFTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 写入完成，是否更新数据区索引？（推荐）.
        '''</summary>
        Friend ReadOnly Property ResText_WFUp() As String
            Get
                Return ResourceManager.GetString("ResText_WFUp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在写入索引.
        '''</summary>
        Friend ReadOnly Property ResText_WI() As String
            Get
                Return ResourceManager.GetString("ResText_WI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引写入完成.
        '''</summary>
        Friend ReadOnly Property ResText_WIF() As String
            Get
                Return ResourceManager.GetString("ResText_WIF", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置写入限速 (MiB/s).
        '''</summary>
        Friend ReadOnly Property ResText_WLimS() As String
            Get
                Return ResourceManager.GetString("ResText_WLimS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 数据高度.
        '''</summary>
        Friend ReadOnly Property ResText_WritePointer() As String
            Get
                Return ResourceManager.GetString("ResText_WritePointer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 数据写入警告.
        '''</summary>
        Friend ReadOnly Property ResText_WriteWarning() As String
            Get
                Return ResourceManager.GetString("ResText_WriteWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 正在写入.
        '''</summary>
        Friend ReadOnly Property ResText_Writing() As String
            Get
                Return ResourceManager.GetString("ResText_Writing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 此前累计写入.
        '''</summary>
        Friend ReadOnly Property ResText_WrittenTotal() As String
            Get
                Return ResourceManager.GetString("ResText_WrittenTotal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 请等待操作完成.
        '''</summary>
        Friend ReadOnly Property ResText_X0() As String
            Get
                Return ResourceManager.GetString("ResText_X0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 操作进行中，是否强制退出？.
        '''</summary>
        Friend ReadOnly Property ResText_X1() As String
            Get
                Return ResourceManager.GetString("ResText_X1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 未索引的数据将会丢失，是否继续.
        '''</summary>
        Friend ReadOnly Property ResText_X2() As String
            Get
                Return ResourceManager.GetString("ResText_X2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 未安全弹出将导致索引不一致，是否继续.
        '''</summary>
        Friend ReadOnly Property ResText_X3() As String
            Get
                Return ResourceManager.GetString("ResText_X3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 设置Barcode失败.
        '''</summary>
        Friend ReadOnly Property StrBCSFail() As String
            Get
                Return ResourceManager.GetString("StrBCSFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to -s                                            不要自动读取索引
        '''  -t &lt;drive&gt;                                    直接读写
        '''  ├  -t 0
        '''  ├  -t TAPE0
        '''  └  -t \\.\TAPE0
        '''                                           
        '''  -f &lt;file&gt;                                     查看本地索引文件：
        '''  └   -f C:\tmp\ltfs\000000.schema
        '''                                           
        '''  -c                                            LTFSConfigurator
        '''                                           
        '''  -l                                            Changer Tool        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property StrCMDHelpText() As String
            Get
                Return ResourceManager.GetString("StrCMDHelpText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  非商业许可.
        '''</summary>
        Friend ReadOnly Property StrDefaultLicense() As String
            Get
                Return ResourceManager.GetString("StrDefaultLicense", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 格式化失败.
        '''</summary>
        Friend ReadOnly Property StrFormatError() As String
            Get
                Return ResourceManager.GetString("StrFormatError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 格式化操作完成.
        '''</summary>
        Friend ReadOnly Property StrFormatFin() As String
            Get
                Return ResourceManager.GetString("StrFormatFin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 索引查看.
        '''</summary>
        Friend ReadOnly Property StrIndexView() As String
            Get
                Return ResourceManager.GetString("StrIndexView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 许可证无效.
        '''</summary>
        Friend ReadOnly Property StrLicenseInvalid() As String
            Get
                Return ResourceManager.GetString("StrLicenseInvalid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SCSI命令执行失败.
        '''</summary>
        Friend ReadOnly Property StrSCSIFail() As String
            Get
                Return ResourceManager.GetString("StrSCSIFail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SCSI命令执行成功.
        '''</summary>
        Friend ReadOnly Property StrSCSISucc() As String
            Get
                Return ResourceManager.GetString("StrSCSISucc", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
