'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\tmp\ltfs\LT0007.schema")>  _
        Public Property IndexAnalyzer_LastFile() As String
            Get
                Return CType(Me("IndexAnalyzer_LastFile"),String)
            End Get
            Set
                Me("IndexAnalyzer_LastFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("L:\")>  _
        Public Property IndexAnalyzer_Src() As String
            Get
                Return CType(Me("IndexAnalyzer_Src"),String)
            End Get
            Set
                Me("IndexAnalyzer_Src") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("U:\")>  _
        Public Property IndexAnalyzer_Dest() As String
            Get
                Return CType(Me("IndexAnalyzer_Dest"),String)
            End Get
            Set
                Me("IndexAnalyzer_Dest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property HashTaskWindow_ReHash() As Boolean
            Get
                Return CType(Me("HashTaskWindow_ReHash"),Boolean)
            End Get
            Set
                Me("HashTaskWindow_ReHash") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IndexAnalyzer_GenCMD() As Boolean
            Get
                Return CType(Me("IndexAnalyzer_GenCMD"),Boolean)
            End Get
            Set
                Me("IndexAnalyzer_GenCMD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FileBrowser_CopyInfo() As Boolean
            Get
                Return CType(Me("FileBrowser_CopyInfo"),Boolean)
            End Get
            Set
                Me("FileBrowser_CopyInfo") = value
            End Set
        End Property
        
        '''<summary>
        '''覆盖已有文件
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("覆盖已有文件"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTFSWriter_OverwriteExist() As Boolean
            Get
                Return CType(Me("LTFSWriter_OverwriteExist"),Boolean)
            End Get
            Set
                Me("LTFSWriter_OverwriteExist") = value
            End Set
        End Property
        
        '''<summary>
        '''写入完成后：
        '''  0-什么都不做
        '''  1-更新数据区索引
        '''  2-更新全部索引
        '''  3-更新全部索引并弹出
        '''
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("写入完成后："&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  0-什么都不做"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  1-更新数据区索引"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  2-更新全部索引"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  3-更新全部索引并弹出"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property LTFSWriter_OnWriteFinished() As Byte
            Get
                Return CType(Me("LTFSWriter_OnWriteFinished"),Byte)
            End Get
            Set
                Me("LTFSWriter_OnWriteFinished") = value
            End Set
        End Property
        
        '''<summary>
        '''容量损失自动停顿开关
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("容量损失自动停顿开关"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTFSWriter_AutoFlush() As Boolean
            Get
                Return CType(Me("LTFSWriter_AutoFlush"),Boolean)
            End Get
            Set
                Me("LTFSWriter_AutoFlush") = value
            End Set
        End Property
        
        '''<summary>
        '''文件标签设置
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("文件标签设置"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LTFSWriter_FileLabel() As String
            Get
                Return CType(Me("LTFSWriter_FileLabel"),String)
            End Get
            Set
                Me("LTFSWriter_FileLabel") = value
            End Set
        End Property
        
        '''<summary>
        '''启用日志
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("启用日志"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTFSWriter_LogEnabled() As Boolean
            Get
                Return CType(Me("LTFSWriter_LogEnabled"),Boolean)
            End Get
            Set
                Me("LTFSWriter_LogEnabled") = value
            End Set
        End Property
        
        '''<summary>
        '''总是更新数据区索引
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("总是更新数据区索引"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTFSWriter_ForceIndex() As Boolean
            Get
                Return CType(Me("LTFSWriter_ForceIndex"),Boolean)
            End Get
            Set
                Me("LTFSWriter_ForceIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property LTFSConf_AutoRefresh() As Boolean
            Get
                Return CType(Me("LTFSConf_AutoRefresh"),Boolean)
            End Get
            Set
                Me("LTFSConf_AutoRefresh") = value
            End Set
        End Property
        
        '''<summary>
        '''重装带前清洁次数
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("重装带前清洁次数"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property LTFSWriter_CleanCycle() As Integer
            Get
                Return CType(Me("LTFSWriter_CleanCycle"),Integer)
            End Get
            Set
                Me("LTFSWriter_CleanCycle") = value
            End Set
        End Property
        
        '''<summary>
        '''计算校验
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("计算校验"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property LTFSWriter_HashOnWriting() As Boolean
            Get
                Return CType(Me("LTFSWriter_HashOnWriting"),Boolean)
            End Get
            Set
                Me("LTFSWriter_HashOnWriting") = value
            End Set
        End Property
        
        '''<summary>
        '''异步校验
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("异步校验"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property LTFSWriter_HashAsync() As Boolean
            Get
                Return CType(Me("LTFSWriter_HashAsync"),Boolean)
            End Get
            Set
                Me("LTFSWriter_HashAsync") = value
            End Set
        End Property
        
        '''<summary>
        '''索引更新间隔（字节）
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("索引更新间隔（字节）"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("38654705664")>  _
        Public Property LTFSWriter_IndexWriteInterval() As Long
            Get
                Return CType(Me("LTFSWriter_IndexWriteInterval"),Long)
            End Get
            Set
                Me("LTFSWriter_IndexWriteInterval") = value
            End Set
        End Property
        
        '''<summary>
        '''容量显示刷新间隔
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("容量显示刷新间隔"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property LTFSWriter_CapacityRefreshInterval() As Integer
            Get
                Return CType(Me("LTFSWriter_CapacityRefreshInterval"),Integer)
            End Get
            Set
                Me("LTFSWriter_CapacityRefreshInterval") = value
            End Set
        End Property
        
        '''<summary>
        '''预读文件数
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("预读文件数"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LTFSWriter_PreLoadFileCount() As Integer
            Get
                Return CType(Me("LTFSWriter_PreLoadFileCount"),Integer)
            End Get
            Set
                Me("LTFSWriter_PreLoadFileCount") = value
            End Set
        End Property
        
        '''<summary>
        '''预读字节数
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("预读字节数"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8388608")>  _
        Public Property LTFSWriter_PreLoadBytes() As Integer
            Get
                Return CType(Me("LTFSWriter_PreLoadBytes"),Integer)
            End Get
            Set
                Me("LTFSWriter_PreLoadBytes") = value
            End Set
        End Property
        
        '''<summary>
        '''禁用分区
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("禁用分区"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTFSWriter_DisablePartition() As Boolean
            Get
                Return CType(Me("LTFSWriter_DisablePartition"),Boolean)
            End Get
            Set
                Me("LTFSWriter_DisablePartition") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(" 非商业许可")>  _
        Public Property Application_License() As String
            Get
                Return CType(Me("Application_License"),String)
            End Get
            Set
                Me("Application_License") = value
            End Set
        End Property
        
        '''<summary>
        '''容量损失判定速度下限
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("容量损失判定速度下限"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property LTFSWriter_AutoCleanDownLim() As Double
            Get
                Return CType(Me("LTFSWriter_AutoCleanDownLim"),Double)
            End Get
            Set
                Me("LTFSWriter_AutoCleanDownLim") = value
            End Set
        End Property
        
        '''<summary>
        '''容量损失判定速度上限
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("容量损失判定速度上限"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("87")>  _
        Public Property LTFSWriter_AutoCleanUpperLim() As Double
            Get
                Return CType(Me("LTFSWriter_AutoCleanUpperLim"),Double)
            End Get
            Set
                Me("LTFSWriter_AutoCleanUpperLim") = value
            End Set
        End Property
        
        '''<summary>
        '''容量损失判定秒数
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("容量损失判定秒数"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property LTFSWriter_AutoCleanTimeThreashould() As Integer
            Get
                Return CType(Me("LTFSWriter_AutoCleanTimeThreashould"),Integer)
            End Get
            Set
                Me("LTFSWriter_AutoCleanTimeThreashould") = value
            End Set
        End Property
        
        '''<summary>
        '''去重
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("去重"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTFSWriter_DeDupe() As Boolean
            Get
                Return CType(Me("LTFSWriter_DeDupe"),Boolean)
            End Get
            Set
                Me("LTFSWriter_DeDupe") = value
            End Set
        End Property
        
        '''<summary>
        '''显示容量损失
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("显示容量损失"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTFSWriter_ShowLoss() As Boolean
            Get
                Return CType(Me("LTFSWriter_ShowLoss"),Boolean)
            End Get
            Set
                Me("LTFSWriter_ShowLoss") = value
            End Set
        End Property
        
        '''<summary>
        '''跳过符号链接
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("跳过符号链接"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property LTFSWriter_SkipSymlink() As Boolean
            Get
                Return CType(Me("LTFSWriter_SkipSymlink"),Boolean)
            End Get
            Set
                Me("LTFSWriter_SkipSymlink") = value
            End Set
        End Property
        
        '''<summary>
        '''显示文件数
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("显示文件数"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTFSWriter_ShowFileCount() As Boolean
            Get
                Return CType(Me("LTFSWriter_ShowFileCount"),Boolean)
            End Get
            Set
                Me("LTFSWriter_ShowFileCount") = value
            End Set
        End Property
        
        '''<summary>
        '''写入开始时切换电源策略
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("写入开始时切换电源策略"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c")>  _
        Public Property LTFSWriter_PowerPolicyOnWriteBegin() As Global.System.Guid
            Get
                Return CType(Me("LTFSWriter_PowerPolicyOnWriteBegin"),Global.System.Guid)
            End Get
            Set
                Me("LTFSWriter_PowerPolicyOnWriteBegin") = value
            End Set
        End Property
        
        '''<summary>
        '''写入结束后切换电源策略
        '''</summary>
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("写入结束后切换电源策略"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("381b4222-f694-41f0-9685-ff5bb260df2e")>  _
        Public Property LTFSWriter_PowerPolicyOnWriteEnd() As Global.System.Guid
            Get
                Return CType(Me("LTFSWriter_PowerPolicyOnWriteEnd"),Global.System.Guid)
            End Get
            Set
                Me("LTFSWriter_PowerPolicyOnWriteEnd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-3.7")>  _
        Public Property LTFSWriter_AutoCleanErrRateLogThreashould() As Double
            Get
                Return CType(Me("LTFSWriter_AutoCleanErrRateLogThreashould"),Double)
            End Get
            Set
                Me("LTFSWriter_AutoCleanErrRateLogThreashould") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.LTFSCopyGUI.My.MySettings
            Get
                Return Global.LTFSCopyGUI.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
