'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings 自动保存功能"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\tmp\ltfs\LT0007.schema")>  _
        Public Property LastFile() As String
            Get
                Return CType(Me("LastFile"),String)
            End Get
            Set
                Me("LastFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("L:\")>  _
        Public Property Src() As String
            Get
                Return CType(Me("Src"),String)
            End Get
            Set
                Me("Src") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("U:\")>  _
        Public Property Dest() As String
            Get
                Return CType(Me("Dest"),String)
            End Get
            Set
                Me("Dest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ReHash() As Boolean
            Get
                Return CType(Me("ReHash"),Boolean)
            End Get
            Set
                Me("ReHash") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property GenCMD() As Boolean
            Get
                Return CType(Me("GenCMD"),Boolean)
            End Get
            Set
                Me("GenCMD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CopyInfo() As Boolean
            Get
                Return CType(Me("CopyInfo"),Boolean)
            End Get
            Set
                Me("CopyInfo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTFSWriter_OverwriteExist() As Boolean
            Get
                Return CType(Me("LTFSWriter_OverwriteExist"),Boolean)
            End Get
            Set
                Me("LTFSWriter_OverwriteExist") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property LTFSWriter_OnWriteFinished() As Byte
            Get
                Return CType(Me("LTFSWriter_OnWriteFinished"),Byte)
            End Get
            Set
                Me("LTFSWriter_OnWriteFinished") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTFSWriter_AutoFlush() As Boolean
            Get
                Return CType(Me("LTFSWriter_AutoFlush"),Boolean)
            End Get
            Set
                Me("LTFSWriter_AutoFlush") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LTFSWriter_FileLabel() As String
            Get
                Return CType(Me("LTFSWriter_FileLabel"),String)
            End Get
            Set
                Me("LTFSWriter_FileLabel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTFSWriter_LogEnabled() As Boolean
            Get
                Return CType(Me("LTFSWriter_LogEnabled"),Boolean)
            End Get
            Set
                Me("LTFSWriter_LogEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property LTFSWriter_ForceIndex() As Boolean
            Get
                Return CType(Me("LTFSWriter_ForceIndex"),Boolean)
            End Get
            Set
                Me("LTFSWriter_ForceIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property LTFSConf_AutoRefresh() As Boolean
            Get
                Return CType(Me("LTFSConf_AutoRefresh"),Boolean)
            End Get
            Set
                Me("LTFSConf_AutoRefresh") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property LTFSWriter_CleanCycle() As Integer
            Get
                Return CType(Me("LTFSWriter_CleanCycle"),Integer)
            End Get
            Set
                Me("LTFSWriter_CleanCycle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property LTFSWriter_HashOnWriting() As Boolean
            Get
                Return CType(Me("LTFSWriter_HashOnWriting"),Boolean)
            End Get
            Set
                Me("LTFSWriter_HashOnWriting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property LTFSWriter_HashAsync() As Boolean
            Get
                Return CType(Me("LTFSWriter_HashAsync"),Boolean)
            End Get
            Set
                Me("LTFSWriter_HashAsync") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("38654705664")>  _
        Public Property LTFSWriter_IndexWriteInterval() As Long
            Get
                Return CType(Me("LTFSWriter_IndexWriteInterval"),Long)
            End Get
            Set
                Me("LTFSWriter_IndexWriteInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("30")>  _
        Public Property LTFSWriter_CapacityRefreshInterval() As Integer
            Get
                Return CType(Me("LTFSWriter_CapacityRefreshInterval"),Integer)
            End Get
            Set
                Me("LTFSWriter_CapacityRefreshInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property LTFSWriter_PreLoadNum() As Integer
            Get
                Return CType(Me("LTFSWriter_PreLoadNum"),Integer)
            End Get
            Set
                Me("LTFSWriter_PreLoadNum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8388608")>  _
        Public Property LTFSWriter_PreLoadBytes() As Integer
            Get
                Return CType(Me("LTFSWriter_PreLoadBytes"),Integer)
            End Get
            Set
                Me("LTFSWriter_PreLoadBytes") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.LTFSCopyGUI.My.MySettings
            Get
                Return Global.LTFSCopyGUI.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
